### PR TITLE
Remove usage of mapping rules list endpoint as it doesnt work

### LINKED ISSUE #88: Incorrect fetching of Mapping rules from 3scale
Metrics associated with mapping rules are fetched without system_name so a default "Hits" is used. The default "Hits" doesnt correspond with default "hits" in 3scale so every backend call results in 404 `<error code="metric_invalid">metric "Hits" is invalid</error>)` resulting in all traffic being rejected.

### PR DESCRIPTION
**Pull request by pehala**
- The endpoint doesn't contain some fields like the system name
- Endpoint was used only as a fallback
Closes #88

### CODE REVIEW

**Review by eguzki — APPROVED** [review]
The content of this PR LGTM

However some tests are failing. If those failing tests are not related to this PR, I suggest to fix them in a separated PR and then rebase this on top of the fix so we can merge with all the tests passing.

**Comment by pehala** [comment]
I will fix the rustfmt, as that is failing on my part of the code. However, Clippy seems to have a problem with other parts of the code that I do not fully understand and I fear I would introduce some regressions.

**Comment by eguzki** [comment]
> I fear I would introduce some

I will give it a try

**Comment by eguzki** [comment]
> > I fear I would introduce some
> 
> I will give it a try

https://github.com/3scale/threescale-wasm-auth/pull/91

**Pull request merged**
